accounts/urls.py
from django.urls import include, path, reverse_lazy
from .views import index, login_view, guest_register, cleaners_view, guestpls, CustomLogoutView, update_profile, CustomPasswordResetView, update_room_status
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('', index, name= 'index'),
    path('login/', login_view, name='login_view'),
    path('register/', guest_register, name='guest_register'),
    path('cleaners/', cleaners_view, name='cleaners_view'),
    path('guesttemp/', guestpls, name='guestpls'),
    path('logout/', CustomLogoutView.as_view(), name='custom_logout'),
    path('update-profile/', update_profile, name='update_profile'),
    path('update_room_status/<int:room_id>/', update_room_status, name='update_room_status'),
    
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done')
    ), name='password_reset'),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    template_name='password_reset_confirm.html',
    success_url=reverse_lazy('accounts:password_reset_complete')
), name='password_reset_confirm'),


    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ), name='password_reset_complete'),
]

bookings/urls.py
from django.urls import path 
from .views import RoomDetailView, BookingListView, CancelBookingView, CheckInView, CheckOutView, BookingConfirmationView

app_name="bookings"

urlpatterns = [
    path('booking_list/', BookingListView.as_view(), name="BookingListView"),
    # path('book/', BookingForm.as_view(), name="BookingView"),
    path('room/<type>/', RoomDetailView.as_view(), name="RoomDetailView"),
    path('booking/cancel/<pk>/', CancelBookingView.as_view(), name="CancelBookingView"),
    path('booking/check_in/<int:room_id>/', CheckInView.as_view(), name="CheckInView"),
    path('booking/check_out/<int:room_id>/', CheckOutView.as_view(), name="CheckOutView"),
    path('booking/confirmation/<int:room_id>/', BookingConfirmationView.as_view(), name="BookingConfirmationView"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('bookings.urls')),
    path('', include('payments.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('', include('hotel.urls')),
    path('', include('loyaltySystem.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path, include
from . import views
from .views import room_list_view, choose_hotel_view

app_name="hotel"

urlpatterns = [
    path('room_list/<int:hotel_id>/', room_list_view, name="RoomListView"),
    path('book/', choose_hotel_view, name='choose_hotel'),
    # path('generate_standard_hotel/', views.generate_standard_hotel, name='generate_standard_hotel')
    #path('hotel_exists/', views.hotel_exists, name='hotel_exists'),
]

hotelReservation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls')),
    path('', include('registration.urls')),
    
]

bookings/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from loyaltySystem.models import LoyaltySystem
from django_project import settings
from hotel.models import Room

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # gets the right user model
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in_date = models.DateTimeField()
    check_out_date = models.DateTimeField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    points_earned = models.IntegerField(default=0)
    
    # Payment status
    class PaymentStatus(models.TextChoices):
        PENDING = 'Pending', 'Pending'
        PAID = 'Paid', 'Paid'
        FAILED = 'Failed', 'Failed'
        REFUNDED = 'Refunded', 'Refunded'

    payment_status = models.CharField(
        max_length=20,
        choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING
    )
    

    def _str_(self):
        return f'{self.user} has booked {self.room} from {self.check_in_date} to {self.check_out_date}'

    # returns the room type
    def get_room_type(self):
        room_types = dict(self.room.ROOM_TYPES)
        room_type = room_types.get(self.room.room_type)
        return room_type

    # calculates nights of stay
    def nights_of_stay(self):
        return (self.check_out_date - self.check_in_date).days  

    # calculates the total price using nights of stay
    def calculate_price(self):
        nights = self.nights_of_stay()
        room_price = self.room.room_price
        total_price = nights * room_price
        
        self.total_price = total_price
        self.save()
        
        return total_price

    # calculates the discount percentage
    def calculate_discount(self, user_points):
        discount_percentage = 0
        if user_points >= 1000:
            max_discount_percentage = 50
            discount_percentage = min((user_points // 1000) * 10, max_discount_percentage)
        return discount_percentage

    # calculates the points earned
    def calculate_points_earned(self):
        
        nights = self.nights_of_stay()
        points_per_night = 100  # Standard tier
        # Update points based on membership tiers
        
        loyalty_details = LoyaltySystem.objects.get(user=self.user)
        membership_tier = loyalty_details.membership_tier
        
        if membership_tier == 'Silver':
            points_per_night = 110
        elif membership_tier == 'Gold':
            points_per_night = 125
        elif membership_tier == 'Diamond':
            points_per_night = 150
        self.points_earned = nights * points_per_night  
        self.save()  
        return nights * points_per_night

    # calculates the price after discount
    def apply_discount(self):
        loyalty_details = LoyaltySystem.objects.get(user=self.user)
        user_points = loyalty_details.total_points
        discount_percentage = self.calculate_discount(user_points)
        price = self.calculate_price()
        
        # Apply discount if applicable
        if discount_percentage > 0:
            discount_amount = (discount_percentage / 100) * price
            discounted_price = price - discount_amount
            price = discounted_price

        return price
    
    # calculates the points deducted
    def calculate_points_deducted(self):
        loyalty_details = LoyaltySystem.objects.get(user=self.user)
        user_points = loyalty_details.total_points
        discount_percentage = self.calculate_discount(user_points)
        points_to_minus = discount_percentage * 100
        loyalty_details.total_points -= points_to_minus
        loyalty_details.save()
        return points_to_minus
        
        # returns the booking url
    def get_cancel_booking_url(self):
        return reverse_lazy('bookings:CancelBookingView', args=[self.pk])
    
    # returns the booking url
    def update_payment_status(self, new_status):
        # Method to update the payment status
        self.payment_status = new_status
        self.save()

bookings/forms.py
from django import forms

# Create your forms here.
# check in and check out dates
class AvailabilityForm(forms.Form):

    check_in_date = forms.DateTimeField(label='Check In', required=True, input_formats=["%Y-%m-%d", ])
    check_out_date = forms.DateTimeField(label='Check Out', required=True, input_formats=["%Y-%m-%d", ])
        

bookings/views.py
from datetime import datetime, time
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.utils import timezone
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy

from hotel.room_status import RoomStatus
from .forms import AvailabilityForm

from bookings.booking_functions.availability import check_availability
from bookings.booking_functions.get_available_rooms import get_available_rooms
from bookings.booking_functions.book_room import book_room

from hotel.room_functions.get_room_type import get_room_type

from bookings.models import Booking
from hotel.models import CheckedInState, CheckedOutState, Room

from django.views.generic import DeleteView

# Create your views here.
class CheckInView(View):
    def get(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        return render(request, 'check_in_success.html', {'room': room})
    
    def post(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        
        room_bookings = Booking.objects.filter(room=room)
        
        if not room_bookings:
            return HttpResponseBadRequest("No bookings found for this room.")
        
        current_date = timezone.now().date()
        current_time = timezone.now().time()
        check_in_time = time(16, 0, 0)  # 4 PM set check-in time
        
        matching_booking = room_bookings.filter(check_in_date__date=current_date).first()
        
        if not matching_booking:
            return HttpResponseBadRequest("Cannot check in: This booking is not for today.")
        elif matching_booking.check_in_date.time() < check_in_time:
            return HttpResponseBadRequest("Cannot check in: Check-in time is before 4 PM.")
        
        if room.room_status != RoomStatus.CLEANED.value:
            return HttpResponseBadRequest("Cannot check in: Room is not clean. Please contact a staff member.")
        
        if room.room_status == RoomStatus.CHECKED_IN.value:
            return HttpResponseBadRequest("You've already checked in!")
        
        # Perform the check-in state transition
        checked_in_state = CheckedInState()
        points_earned = checked_in_state.handle(room)
        
        if points_earned is not None:
            # Assuming successful check-in scenario where points are earned
            room.save()
            return render(request, 'check_in_success.html', {'room': room, 'points_earned': points_earned})
        else:
            # Handle error scenario where no booking is found for today
            return HttpResponseBadRequest("Error: No booking found for today.")

# check out view
class CheckOutView(View):
    def get(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        return render(request, 'check_out_success.html', {'room': room})
    
    def post(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        

        checked_out_state = CheckedOutState()
        checked_out_state.handle(room) 

        room.save()
        return render(request, 'check_out_success.html', {'room': room})


# booking list view. shows bookings
class BookingListView(ListView):
    model = Booking
    template_name = 'booking_list_view.html'
    
    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list
    
    
#     actual room view
class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        room_type = self.kwargs.get('type', None)
        room_type_name = get_room_type(room_type)
        form = AvailabilityForm()

        if room_type_name is not None:
            context = {
                'room_type': room_type_name,
                'form': form,
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Invalid room type')

    def post(self, request, *args, **kwargs):
        room_type = self.kwargs.get('type', None)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            check_in_time = data['check_in_date']
            check_out_time = data['check_out_date']

            # Set the time to 4:00 PM for both check-in and check-out
            check_in_time = check_in_time.replace(hour=16, minute=0, second=0)
            check_out_time = check_out_time.replace(hour=16, minute=0, second=0)

            if check_in_time.date() < timezone.now().date():
                return HttpResponse('Check-in date cannot be in the past.')

            if check_out_time <= check_in_time:
                return HttpResponse('Check-out date should be after the check-in date.')

            available_rooms = get_available_rooms(room_type, check_in_time, check_out_time)

            if available_rooms:
                booking = book_room(request, available_rooms[0], check_in_time, check_out_time)

                formatted_check_in = check_in_time.strftime("%Y-%m-%d %H:%M:%S")
                formatted_check_out = check_out_time.strftime("%Y-%m-%d %H:%M:%S")

                context = {
                    'room_type': room_type,
                    'check_in': formatted_check_in,
                    'check_out': formatted_check_out,
                    'nights_stay': booking.nights_of_stay(),
                    'total_price': booking.apply_discount(),
                    'points_earned': booking.calculate_points_earned(),
                    'points_used': booking.calculate_points_deducted(),
                }

                # messages.success(
                #     self.request,
                #     f'Your booking for a {room_type} room from {formatted_check_in} to {formatted_check_out} has been confirmed! Thank you for choosing us.'
                # )

                # Fetch the hotel ID dynamically from the booked room or replace it with the correct logic
                hotel_id = None
                if booking and booking.room and booking.room.hotel:
                    hotel_id = booking.room.hotel.id

                if hotel_id:
                    room_list_url = reverse('hotel:RoomListView', args=[hotel_id])
                    return redirect('paypal-payment', booking_id=booking.id)
                    # return HttpResponseRedirect(room_list_url)
                else:
                    return HttpResponse('Hotel not found!')
            else:
                return HttpResponse('No rooms available for the selected dates. Please try a different room or date.')
        else:
            return HttpResponse('Form data is not valid.')

# booking confirmation view      
        
class BookingConfirmationView(View):
    def get(self, request, room_id):
        booking = Booking.objects.get(pk=room_id)

        context = {
            'room_type': booking.get_room_type(),
            'check_in': booking.check_in_date,
            'check_out': booking.check_out_date,
            'nights_stay': booking.nights_of_stay(),
            'total_price': booking.calculate_price(),
            'points_earned': booking.calculate_points_earned(),
            'points_used': booking.calculate_points_deducted(),
        }
        
        print(context)
        print(booking.__dict__)

        return render(request, 'booking_confirmation.html', context)

# booking cancel view
class CancelBookingView(DeleteView):
    model = Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('bookings:BookingListView')

bookings/templates/availibility_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book a Room</title>
</head>
<body>
    <form action="" method="POST">
        {{form.as_p}}
        {% csrf_token%}
        <button type="submit">Book my room!</button>
    </form>
    
</body>
</html>

bookings/templates/booked_room_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <div class="home">
        <!-- sends back to rooms view -->
        <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
    </div>

</body>
</html>

bookings/templates/booked_room_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Confirmation</title>
</head>
<body>
    <div class="confirmation">
        <h1>Booking Confirmation</h1>
        <p>Your booking for a {{ room_type }} room has been confirmed!</p>
        <p>Check-in: {{ check_in }}</p>
        <p>Check-out: {{ check_out }}</p>
    </div>

    <div class="home">
        <!-- sends back to rooms view -->
        <a href="{% url 'bookings:BookingListView' %}"><i class="fas fa-arrow-alt-circle-left"></i>Home</a>
    </div>
</body>
</html>

bookings/templates/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="{% static 'css/room_detail_view.css' %}">

</head>

<body>

    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <div class="room">

            <div class="home">
                <a href="{% if hotel_id %}{% url 'hotel:RoomListView' hotel_id=hotel_id %}{% endif %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- room info -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- cancelling booking -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you want to cancel this booking?</h2>
                <h3>Details</h3>
                <p>Room: {{ booking.room }}</p>
                <p>Check-in Date: {{ booking.check_in_date }}</p>
                <p>Check-out Date: {{ booking.check_out_date }}</p>
                <p>Total Price: {{ booking.total_price }}</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit">Confirm Cancellation</button>

            </form>

        </div> <!-- END Room  -->

    </div> <!-- END Main Content  -->

</body>

</html>

bookings/templates/booking_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="confirmation">
        <h1>Booking Confirmation</h1>
        <p>Your booking for a {{ room_type }} room has been confirmed!</p>
        <p>Check-in: {{ check_in }}</p>
        <p>Check-out: {{ check_out }}</p>
        <p>Nights staying: {{ nights_stay }}</p>
        <p>Total Price: {{ total_price }}</p>
        <p>Points earned: {{ points_earned }} Points will be added to account upon checking in</p>
        <p>Points deducted: {{ points_used }}</p>
    </div>
    
    <div class="home">
        <!-- sends to list of bookings -->
        <a href="{% url 'bookings:BookingListView' %}"><i class="fas fa-arrow-alt-circle-left"></i>Home</a>
    </div>
</body>
</html>

bookings/templates/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/booking_list_view.css' %}">
    <div class="home">
        <!-- Back to Home -->
        <div class="home">
            {% csrf_token %}
            <a href="{% url 'accounts:guestpls' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
        </div>
    </div>
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome {{user}}</h2>
                <p>View your bookings here.</p>
            </div>
        </div>
        <div class="bookings">
            {% csrf_token %}
            {% for booking in booking_list %}
            <div class="booking">
                <div class="image">
                    <img src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
                </div>
                <div class="category">
                    <h2>{{booking.get_room_type}} Suite</h2>
                </div>
                <div class="from">
                    <h3>From: {{booking.check_in_date}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.check_out_date}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{booking.room.room_beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{booking.room.room_capacity}}</h3>
                </div>
                <div class="actions">
                    <!-- Check-in button -->
                    <div class="check-btns">
                        <form action="{% url 'bookings:CheckInView' room_id=booking.room_id %}" method="post" class="check">
                            {% csrf_token %}
                            <button type="submit">Check-in</button>
                        </form>
                        <form action="{% url 'bookings:CheckOutView' room_id=booking.room_id %}" method="post" class="check">
                            {% csrf_token %}
                            <button type="submit">Check-out</button>
                        </form>
                    </div>
                    <div class="cancel">
                        <!-- Cancel button -->
                        <a href="{% url 'bookings:CancelBookingView' pk=booking.pk %}" class="invisible">
                            <i class="far fa-2x fa-times-zcircle"> Cancel Booking</i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
</body>

</html>

bookings/templates/check_in_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checked-In</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f8f8f8;
            text-align: center;
            color: #555;
        }

        div {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h1 {
            color: #007bff;
        }

        p {
            font-size: 20px;
            color: #333;
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div>
        <h1>Welcome!</h1>
        <p>You've successfully checked in, and points have been added to your account.</p>
    </div>
</body>
<div class="header">
    <div class="home">
        <div class="home">
            {% csrf_token %}
            <a href="{% url 'accounts:guestpls' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
        </div>
    </div>

</div>
</html>

bookings/templates/check_out_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checked-In</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f8f8f8;
            text-align: center;
            color: #555;
        }

        div {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h1 {
            color: #007bff;
        }

        p {
            font-size: 20px;
            color: #333;
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div>
        <h1>Thank you for staying!</h1>
        <p>You've successfully checked-out. See you soon!</p>
    </div>
</body>
<div class="header">
    <div class="home">
        <div class="home">
            {% csrf_token %}
            <a href="{% url 'accounts:guestpls' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
        </div>
    </div>

</div>
</html>

bookings/templates/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'css/room_detail_view.css' %}"> 

</head>

<body>

    <div class="content">

        <div class="image">
            <img src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
                    
        </div>

        <!-- room details -->
        <div class="room">

            <!-- gets hotel id to send back to list view -->
            <div class="home">
                <a href="{% if hotel_id %}{% url 'hotel:RoomListView' hotel_id=hotel_id %}{% endif %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>

            </div>

            <div class="room-info">
                <h1>{{room_type}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <div class="input-div">
                    <label for="id_check_in_date">Check In : </label>
                    <input type="date" id="id_check_in_date" name="check_in_date">
                </div>

                <div class="input-div">
                    <label for="id_check_out_date">Check Out : </label>
                    <input type="date" id="id_check_out_date" name="check_out_date">
                </div>

                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>