django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('bookings.urls')),
    path('', include('payments.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('', include('hotel.urls')),
    path('', include('loyaltySystem.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path, include
from . import views
from .views import room_list_view, choose_hotel_view

app_name="hotel"

urlpatterns = [
    path('room_list/<int:hotel_id>/', room_list_view, name="RoomListView"),
    path('book/', choose_hotel_view, name='choose_hotel'),
    # path('generate_standard_hotel/', views.generate_standard_hotel, name='generate_standard_hotel')
    #path('hotel_exists/', views.hotel_exists, name='hotel_exists'),
]

hotelReservation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls')),
    path('', include('registration.urls')),
    
]

hotel/models.py
from datetime import date
import logging
from django.db import models
from loyaltySystem.models import LoyaltySystem
from hotel.room_status import RoomStatus

# creates a hotel
class Hotel(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    number_of_rooms = models.PositiveIntegerField()

    def __str__(self):
        return self.name

'''
To stop circular dependency, we can use the string 'Room' instead of the Room class
'''
# junction table
class HotelRoom(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room = models.ForeignKey('Room', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.hotel.name} - Room {self.room.room_number}"

class Room(models.Model):
    ROOM_TYPES = (
        ('SINGLE', 'Single'),
        ('DOUBLE', 'Double'),
        ('FAMILY', 'Family'),
    )

    room_number = models.IntegerField()
    room_type = models.CharField(max_length=20, choices=ROOM_TYPES)
    room_beds = models.IntegerField()
    room_capacity = models.IntegerField()
    room_price = models.IntegerField()
    room_description = models.TextField()
    room_image = models.ImageField(upload_to='static/images')
    hotel = models.ForeignKey(Hotel, related_name='rooms', on_delete=models.CASCADE, default=1)

    room_status = models.CharField(
        max_length=20,
        choices=[
            (status.value, status.name) for status in RoomStatus
        ],
        default=RoomStatus.CLEANED.value,
    )
    hotel = models.ForeignKey(Hotel, related_name='rooms', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.room_number}: {self.room_type} with {self.room_beds} beds for {self.room_capacity} people'

    def set_status(self, new_status):
        self.room_status = new_status
        self.save()

    def handle_state(self, state):
        return state.handle(self)

class RoomState:
    def handle(self, room):
        pass

class CheckedInState(RoomState):
    def handle(self, room):
        today = date.today()

        # Get all bookings for this room
        room_bookings = room.booking_set.filter(check_in_date__date=today)

        relevant_booking = room_bookings.first()
    

        if relevant_booking:
            relevant_booking.calculate_points_earned()
            user = relevant_booking.user
            loyalty_system = LoyaltySystem.objects.get(user=user)
            loyalty_system.total_points += relevant_booking.points_earned
            loyalty_system.update_membership_tier()
            loyalty_system.save()

            room.set_status(RoomStatus.CHECKED_IN.value)

            logger = logging.getLogger(__name__)
            logger.info(f"Room {room.room_number} checked in successfully")

            return relevant_booking.points_earned
        else:
            logger = logging.getLogger(__name__)
            logger.error(f"No booking found for today for Room {room.room_number}")
            return None

class CheckedOutState(RoomState):
    def handle(self, room):
        room.set_status(RoomStatus.CHECKED_OUT.value)
        logger = logging.getLogger(__name__)
        logger.info(f"Room {room.room_number} checked out successfully")

class CleanedState(RoomState):
    def handle(self, room):
        room.set_status(RoomStatus.CLEANED.value)
        logger = logging.getLogger(__name__)
        logger.info(f"Room {room.room_number} is clean!")

    def check_out(self, room):
        room.set_status(RoomStatus.CHECKED_OUT.value)
        logger = logging.getLogger(__name__)
        logger.info(f"Room {room.room_nmber} checked out successfully")    

hotel/views.py
from django.shortcuts import get_object_or_404, render

from hotel.hotel_functions.room_creator import create_rooms_for_standard_hotel
from .models import Hotel, Room

from hotel.room_functions.get_room_list import get_room_type_url_list
from hotel.hotel_functions.create_rooms import create_rooms_for_hotel

# Create your views here.

# Display the list of hotels for selection
def choose_hotel_view(request):
    hotels = Hotel.objects.all()
    context = {'hotels': hotels}
    return render(request, 'choose_hotel.html', context)

#  seeimg rooms
def room_list_view(request, hotel_id):
    hotel = get_object_or_404(Hotel, id=hotel_id)
    rooms = Room.objects.filter(hotel=hotel)  # Filter rooms related to the selected hotel
    room_list = get_room_type_url_list(rooms)
    context = {'hotel': hotel, 'room_list': room_list} 
    return render(request, 'room_list_view.html', context)


def generate_hotel_with_rooms(hotel_name, num_rooms):
    hotel_exists = Hotel.objects.filter(name=hotel_name).exists()

    if hotel_exists:
        existing_hotel = Hotel.objects.get(name=hotel_name)
        return False, existing_hotel  
    else:
        # Create a new hotel with the provided name and number of rooms
        new_hotel = Hotel.objects.create(name=hotel_name, number_of_rooms=num_rooms)

        # Generate rooms for the hotel
        created_rooms = create_rooms_for_hotel(new_hotel, num_rooms)

        if created_rooms:
            return True, created_rooms  
        else:
            return False, new_hotel  

hotel/templates/choose_hotel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Hotel</title>

    <link rel="stylesheet" href="{% static 'css/choose_hotel.css' %}"> 
</head>

<body>
 
    <h1 id="brand">Choose Hotel</h1>

 
    <div class="content">
        {% if hotels %}
            <div class="button-container">
                {% for hotel in hotels %}
                    <a href="{% url 'hotel:RoomListView' hotel_id=hotel.id %}" class="hotel-button">{{ hotel.name }}</a>
                {% endfor %}
            </div>
        {% else %}
            <p>No hotels available.</p>
        {% endif %}
    </div>
</body>
</html>

hotel/templates/room_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel</title>
    <link rel="stylesheet" href="{% static 'css/room_list_view.css' %}">
</head>

<body>
    <!-- Brand -->
    <h1 id="brand">{% if hotel %}Rooms at {{ hotel.name }}{% else %}Hotel{% endif %}</h1>


    <div class="content">
        {% if room_list %}
            {% for room_type, room_url in room_list %}
                <a href="{% url 'hotel:RoomListView' hotel.id %}" class="room-link">
                <div class="room">
                    <a href="{{room_url}}">
                        <div class="image">
                            {% if room_image %}
                                <img src="{{ room_image }}">
                            {% else %}
                                <img
                                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
                            
                            {% endif %}
                        </div>
                        <h2>{{room_type}} Room</h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
                    </a>
                </div>
            </a>
            {% endfor %}
        {% else %}
            <p>No rooms available.</p>
        {% endif %}

    </div>
</body>

</html>

hotel/templates/standard_hotel_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Standard Hotel Created</title>
</head>
<body>
    <h1>Standard Hotel: {{ existing_hotel.name }}</h1>
    
    <h2>Hotel Information</h2>
    <p><strong>Address:</strong> {{ existing_hotel.address }}</p>
    <p><strong>Number of Rooms:</strong> {{ existing_hotel.number_of_rooms }}</p>

    <h2>Rooms</h2>
    <ul>
        {% for room in created_rooms %}
            <li>
                Room {{ room.room_number }} - Type: {{ room.room_type }} - Beds: {{ room.room_beds }} - Capacity: {{ room.room_capacity }}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

hotel/templates/standard_hotel_exists.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Hotel already ya idiot</p>
</body>
</html>